In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
random_1 =tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2,random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [5,2]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  2]], dtype=int32)>

###### Operation Level Seed

In [ ]:
#different result every time

tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

###### Global Level Seed

In [ ]:
#mixed only once
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  2],
       [10,  7]], dtype=int32)>

#### Numpy array into tensors

In [ ]:
import numpy as np 
numpy_A = np.arange(1, 30, 5, dtype = np.int32)
numpy_A

array([ 1,  6, 11, 16, 21, 26], dtype=int32)

In [ ]:
numpy_to_tensor = tf.constant(numpy_A)
numpy_to_tensor

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 1,  6, 11, 16, 21, 26], dtype=int32)>

In [ ]:
numpy_to_tensor2 = tf.constant(numpy_A, shape=(2,3,1))
numpy_to_tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[ 1],
        [ 6],
        [11]],

       [[16],
        [21],
        [26]]], dtype=int32)>

In [ ]:
numpy_to_tensor3 = tf.constant(numpy_A, shape=(2,3))
numpy_to_tensor3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  6, 11],
       [16, 21, 26]], dtype=int32)>

In [ ]:
#get first 2 elements of each dimensions
rank_4_tensor =tf.ones(shape=(2,3,4,5))
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor 
rank_2_tensor = tf.zeros(shape=(2,3))
print(rank_2_tensor)
rank_2_tensor.ndim

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


2

In [ ]:
#Get last item of each of row our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
#Add in extra dimension to out rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

##Maniputaling Tensor

In [ ]:
tensor = tf.constant([[8,1],
                     [3,2]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 1],
       [3, 2]], dtype=int32)>

In [ ]:
print(tensor[1][1] + 5)
print(tensor[:1][:1] + 10)
print(tensor[1::1] + 2)


tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor([[18 11]], shape=(1, 2), dtype=int32)
tf.Tensor([[5 4]], shape=(1, 2), dtype=int32)


In [ ]:
tf.multiply(tensor , 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16,  2],
       [ 6,  4]], dtype=int32)>

####Matrix Multiplication

In [ ]:
tf.matmul(tensor, [[3,2],[1,2]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 18],
       [11, 10]], dtype=int32)>

In [ ]:
tensor @ [[3,2],[1,2]]
#tensor @ [[3,2],[1,2],[3,2]] Matrix size-incompatible
#Numbers on the inside must match 3x"3" @ "3"x2 = 3x2
#Solution:
#1: Create new matrix
#2: tf.reshape(tensor, shape(x,y)) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 18],
       [11, 10]], dtype=int32)>

In [ ]:
X = tf.constant([[1,2],[3,4],[5,6]])

X,tf.transpose(X) , tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

#### Chancing the datatype of a tensor

In [ ]:
Y = tf.constant([1.7, 2.3])
Y.dtype

tf.float32

In [ ]:
Z = tf.constant([2, 5])
Z.dtype

tf.int32

In [ ]:
#Chance from float32 to float16 (reduced precision)
D = tf.cast(Y,dtype = tf.float16)
D.dtype

tf.float16

#### One hot encoding

In [ ]:
some_list = [3,5,7,1,5]
some_list_depth = 5

In [ ]:
tf.one_hot(some_list , some_list_depth, on_value="on", off_value="off" )

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'off', b'off', b'off', b'on', b'off'],
       [b'off', b'off', b'off', b'off', b'off'],
       [b'off', b'off', b'off', b'off', b'off'],
       [b'off', b'on', b'off', b'off', b'off'],
       [b'off', b'off', b'off', b'off', b'off']], dtype=object)>

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Tue Aug  2 18:55:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    31W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------